import type { PartTile } from "../types";

// Antenna accessory — single bobbed antenna sprouting from the head.
export const antennaAccessory = {
  id: "antenna",
  label: { en: "Antenna", zh: "触角" },
  tile: [
    "                                ",
    "               bbb              ",
    "              bbbbb             ",
    "               bbb              ",
    "                a               ",
    "                a               ",
    "                a               ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
} satisfies PartTile;
