import type { PartTile } from "../types";

// Bow accessory — small bow perched on the side of the head.
export const bowAccessory = {
  id: "bow",
  label: { en: "Bow", zh: "蝴蝶结" },
  tile: [
    "                                ",
    "                                ",
    "                                ",
    "         aa            aa       ",
    "        aaaa          aaaa      ",
    "        aabba        abbaa      ",
    "         aabbaa    aabbaa       ",
    "           aabba  abbaa         ",
    "             abbaabba           ",
    "              abbbba            ",
    "             abbaabba           ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
} satisfies PartTile;
