import type { PartTile } from "../types";

// Hat accessory — small pointed cap sits on top of the head crown.
export const hatAccessory = {
  id: "hat",
  label: { en: "Hat", zh: "帽子" },
  tile: [
    "                                ",
    "                aa              ",
    "               aaaa             ",
    "              aaaaaa            ",
    "             aaaaaaaa           ",
    "          bbbbbbbbbbbbbb        ",
    "          bbbbbbbbbbbbbb        ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
} satisfies PartTile;
