import type { PartTile } from "../types";

// Leaf-on-head accessory — small leaf perched on top of the head.
export const leafAccessory = {
  id: "leaf",
  label: { en: "Leaf", zh: "叶子" },
  tile: [
    "                                ",
    "                aa              ",
    "               aabba            ",
    "              aabbbba           ",
    "             aabbbbbba          ",
    "              aabbbba           ",
    "               aabba            ",
    "                aa              ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
} satisfies PartTile;
