#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  argbFromHex,
  hexFromArgb,
} from "../../../apps/web/src/vendor/material-color-utilities/string_utils.ts";
import { TonalPalette } from "../../../apps/web/src/vendor/material-color-utilities/tonal_palette.ts";
import { pickForeground } from "./contrast.ts";
import { evaluateCurve, SYSTEM_HUES, SYSTEM_PALETTE_TONES } from "./source.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.join(__dirname, "../../..");

// Per-StyleX docs: `.stylex.ts` files may only export `defineVars` /
// `defineConsts` calls. The codegen emits one file per hue with two consts
// groups — `<slug>` for hex strings, `<slug>_rgb` for the comma-separated
// channel form (used to compose `rgba(${var}, <alpha>)`).
//
// After the StyleX Babel plugin runs, the `stylex.defineConsts(...)` call is
// AST-replaced with the literal object, so consumer code can read
// `hue._tone` and get the actual hex string — in `stylex.create`,
// `stylex.defineVars`, inline `style={{}}`, canvas APIs, anywhere. Without
// the plugin transform (e.g. when imported from a test harness that doesn't
// configure StyleX) the runtime `stylex.defineConsts` call throws — so this
// codegen's own unit tests re-derive values from source rather than load
// the generated files.
const outputDir = path.join(
  projectRoot,
  "packages",
  "ui",
  "src",
  "_generated",
  "palette",
);

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

interface ToneOutput {
  readonly bg: string;
  readonly fg: string;
  readonly rgb: string;
}

interface ResolvedHue {
  readonly name: string;
  readonly source: string;
  readonly slug: string;
  readonly tones: ReadonlyMap<number, ToneOutput>;
}

function hexToRgbChannels(hex: string): string {
  const normalized = hex.startsWith("#") ? hex.slice(1) : hex;
  const r = Number.parseInt(normalized.slice(0, 2), 16);
  const g = Number.parseInt(normalized.slice(2, 4), 16);
  const b = Number.parseInt(normalized.slice(4, 6), 16);
  return `${String(r)},${String(g)},${String(b)}`;
}

function resolve(): readonly ResolvedHue[] {
  return SYSTEM_HUES.map((hue) => {
    const palette = TonalPalette.fromInt(argbFromHex(hue.source));
    const tones = new Map<number, ToneOutput>();
    for (const t of SYSTEM_PALETTE_TONES) {
      const shift = evaluateCurve(t, hue.curve);
      const adjusted = Math.max(0, Math.min(100, t + shift));
      const bg = hexFromArgb(palette.tone(adjusted)).toUpperCase();
      const fg = pickForeground(bg);
      const rgb = hexToRgbChannels(bg);
      tones.set(t, { bg, fg, rgb });
    }
    return {
      name: hue.name,
      source: hue.source,
      slug: slugify(hue.name),
      tones,
    };
  });
}

function renderHueFile(hue: ResolvedHue): string {
  // Two consts groups per hue:
  //   <slug>     — hex strings, e.g. gray._92 === "#E9E8E4"
  //   <slug>_rgb — comma-separated RGB channels for rgba() composition,
  //                e.g. gray_rgb._92 === "233,232,228"
  //
  // The StyleX plugin AST-replaces `stylex.defineConsts(...)` with the literal
  // object, so each group works in stylex contexts (inlined into CSS at
  // compile time) AND at runtime (`hue._92` is the actual string). One source
  // of truth, no duplicate exports.
  //
  // Per StyleX rules, `.stylex.ts` files may only export `defineVars` /
  // `defineConsts` calls — so hue metadata (name, source) and foreground
  // contrast colors live in `palette-table.ts` (plain `.ts`) where the showcase
  // already aggregates them.
  const entriesFor = (key: "bg" | "rgb") =>
    SYSTEM_PALETTE_TONES.map((t) => {
      const swatch = hue.tones.get(t);
      if (!swatch) return "";
      return `  _${String(t)}: "${swatch[key]}",`;
    }).filter(Boolean);

  return [
    "// AUTO-GENERATED by packages/system-palette-codegen — do not edit.",
    "// To regenerate: pnpm codegen:palette",
    "",
    'import * as stylex from "@stylexjs/stylex";',
    "",
    `export const ${hue.slug} = stylex.defineConsts({`,
    ...entriesFor("bg"),
    "});",
    "",
    `export const ${hue.slug}_rgb = stylex.defineConsts({`,
    ...entriesFor("rgb"),
    "});",
    "",
  ].join("\n");
}

function renderTableFile(hues: readonly ResolvedHue[]): string {
  const tonesLiteral = SYSTEM_PALETTE_TONES.join(", ");
  // The showcase is the only consumer. `bg` values come from the `.stylex.ts`
  // consts groups (which at runtime are literal objects, so member access
  // yields the actual hex string); `fg`, `name`, and `source` are inlined as
  // plain string literals — they don't belong in a `.stylex.ts` file (the
  // StyleX rule forbids non-stylex exports there) and the showcase needs them
  // at runtime anyway.
  // The hue primitives live in the sibling `hues/` folder; this derived table
  // is the lone `.ts` at the palette root.
  // Sort imports alphabetically to satisfy the project's import-x/order
  // lint rule; functional order doesn't matter (each import is independent).
  const imports = [...hues]
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map((h) => `import { ${h.slug} } from "./hues/${h.slug}.stylex.ts";`)
    .join("\n");

  const entries = hues
    .map((h) => {
      const toneEntries = SYSTEM_PALETTE_TONES.map((t) => {
        const swatch = hue_tones(h, t);
        return `      ${String(t)}: { bg: ${h.slug}._${String(t)}, fg: "${swatch.fg}" },`;
      }).join("\n");
      return `  {
    name: "${h.name}",
    source: "${h.source}",
    tones: {
${toneEntries}
    },
  }`;
    })
    .join(",\n");

  return `// AUTO-GENERATED by packages/system-palette-codegen — do not edit.
// To regenerate: pnpm codegen:palette

${imports}

export const SYSTEM_PALETTE_TONES = [${tonesLiteral}] as const;

export type SystemPaletteTone = (typeof SYSTEM_PALETTE_TONES)[number];

export interface SystemToneSwatch {
  readonly bg: string;
  readonly fg: string;
}

export interface SystemHuePalette {
  readonly name: string;
  readonly source: string;
  readonly tones: Readonly<Record<SystemPaletteTone, SystemToneSwatch>>;
}

export const systemPalette: readonly SystemHuePalette[] = [
${entries},
];
`;
}

function hue_tones(hue: ResolvedHue, t: number): ToneOutput {
  const swatch = hue.tones.get(t);
  if (!swatch) throw new Error(`Hue ${hue.name} has no tone ${String(t)}`);
  return swatch;
}

function writeFileSyncIfChanged(filePath: string, content: string): void {
  if (
    fs.existsSync(filePath) &&
    fs.readFileSync(filePath, "utf8") === content
  ) {
    return;
  }
  fs.writeFileSync(filePath, content, "utf8");
}

function cleanStaleFiles(
  dir: string,
  keep: ReadonlySet<string>,
): readonly string[] {
  if (!fs.existsSync(dir)) return [];
  const removed: string[] = [];
  for (const entry of fs.readdirSync(dir)) {
    const fullPath = path.join(dir, entry);
    if (!fs.statSync(fullPath).isFile()) continue;
    if (!entry.endsWith(".ts")) continue;
    if (keep.has(entry)) continue;
    fs.unlinkSync(fullPath);
    removed.push(entry);
  }
  return removed;
}

const hues = resolve();
const huesDir = path.join(outputDir, "hues");
fs.mkdirSync(huesDir, { recursive: true });

const expectedHueFiles = new Set<string>();
for (const hue of hues) {
  const filename = `${hue.slug}.stylex.ts`;
  expectedHueFiles.add(filename);
  writeFileSyncIfChanged(path.join(huesDir, filename), renderHueFile(hue));
}
writeFileSyncIfChanged(
  path.join(outputDir, "palette-table.ts"),
  renderTableFile(hues),
);

// Clean each level to its own expected set. Sweeping the palette root (keeping
// only the derived table) also removes the pre-subfolder flat layout — the old
// `table.ts` plus the hue files that used to sit alongside it.
const removed = [
  ...cleanStaleFiles(huesDir, expectedHueFiles),
  ...cleanStaleFiles(outputDir, new Set<string>(["palette-table.ts"])),
];

console.log(
  `Wrote ${String(hues.length)} hue files to ${huesDir} + palette-table.ts to ${outputDir}`,
);
if (removed.length > 0) {
  console.log(`Removed stale files: ${removed.join(", ")}`);
}

// Remove legacy outputs from prior layouts so they don't linger.
const legacyTargets = [
  path.join(
    projectRoot,
    "apps",
    "web",
    "src",
    "_generated",
    "system-palette.ts",
  ),
  path.join(projectRoot, "apps", "web", "src", "_generated", "palette"),
  path.join(
    projectRoot,
    "packages",
    "ui",
    "src",
    "_generated",
    "palette-values",
  ),
];
for (const target of legacyTargets) {
  if (!fs.existsSync(target)) continue;
  fs.rmSync(target, { recursive: true, force: true });
  console.log(`Removed legacy ${target}`);
}
