import type { PartTile } from "#src/pixel-creature-creator/sprite/sprites/types.ts";

// Glasses accessory — round goggles aligned with eye row.
export const glassesAccessory = {
  id: "glasses",
  label: { en: "Glasses", zh: "眼镜" },
  tile: [
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "          aaaaa    aaaaa        ",
    "         abbbbba  abbbbba       ",
    "         ab   ba  ab   ba       ",
    "         ab   ba  ab   ba       ",
    "         abbbbba  abbbbba       ",
    "          aaaaaaaaaaaaaa        ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
} satisfies PartTile;
