import type { PartTile } from "#src/pixel-creature-creator/sprite/sprites/types.ts";

// Scarf accessory — wraps around the neck (between head and body).
export const scarfAccessory = {
  id: "scarf",
  label: { en: "Scarf", zh: "围巾" },
  tile: [
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "       aaaaaaaaaaaaaaaaa        ",
    "      babababababababababa      ",
    "       aaaaaaaaaaaaaaaaa        ",
    "             aaaa               ",
    "             abba               ",
    "             abba               ",
    "             aaaa               ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
} satisfies PartTile;
