"use server";

import "server-only";
import { tmdbGet, type QueryParams } from "../utils/tmdb-client";

/**
 * Server functions for TMDB APIs - can be called from server components directly
 * or from client components via API routes. Each function accepts a single params object.
 *
 * This file is auto-generated by packages/tmdb-codegen/generator.js
 * Do not edit manually - changes will be overwritten.
 */

export async function discoverMovies(
  params?: QueryParams<"/3/discover/movie", "get">,
) {
  return tmdbGet("/3/discover/movie", {
    "vote_average.gte": 3,
    "vote_count.gte": 300,
    ...params,
  });
}

export async function discoverTvShows(
  params?: QueryParams<"/3/discover/tv", "get">,
) {
  return tmdbGet("/3/discover/tv", {
    "vote_average.gte": 3,
    "vote_count.gte": 300,
    ...params,
  });
}

export async function getConfiguration(
  params?: QueryParams<"/3/configuration", "get">,
) {
  return tmdbGet("/3/configuration", params);
}

export async function getMovieCredits(
  params: { movie_id: string } & QueryParams<
    "/3/movie/{movie_id}/credits",
    "get"
  >,
) {
  const { movie_id, ...queryParams } = params;
  return tmdbGet("/3/movie/{movie_id}/credits", queryParams, { movie_id });
}

export async function getMovieDetails(
  params: { movie_id: string } & QueryParams<"/3/movie/{movie_id}", "get">,
) {
  const { movie_id, ...queryParams } = params;
  return tmdbGet("/3/movie/{movie_id}", queryParams, { movie_id });
}

export async function getMovieGenres(
  params?: QueryParams<"/3/genre/movie/list", "get">,
) {
  return tmdbGet("/3/genre/movie/list", params);
}

export async function getMovieRecommendations(
  params: { movie_id: string } & QueryParams<
    "/3/movie/{movie_id}/recommendations",
    "get"
  >,
) {
  const { movie_id, ...queryParams } = params;
  return tmdbGet("/3/movie/{movie_id}/recommendations", queryParams, {
    movie_id,
  });
}

export async function getMovieReviews(
  params: { movie_id: string } & QueryParams<
    "/3/movie/{movie_id}/reviews",
    "get"
  >,
) {
  const { movie_id, ...queryParams } = params;
  return tmdbGet("/3/movie/{movie_id}/reviews", queryParams, { movie_id });
}

export async function getMovieVideos(
  params: { movie_id: string } & QueryParams<
    "/3/movie/{movie_id}/videos",
    "get"
  >,
) {
  const { movie_id, ...queryParams } = params;
  return tmdbGet("/3/movie/{movie_id}/videos", queryParams, { movie_id });
}

export async function getMovieWatchProviders(
  params: { movie_id: string } & QueryParams<
    "/3/movie/{movie_id}/watch/providers",
    "get"
  >,
) {
  const { movie_id, ...queryParams } = params;
  return tmdbGet("/3/movie/{movie_id}/watch/providers", queryParams, {
    movie_id,
  });
}

export async function getPersonCombinedCredits(
  params: { person_id: string } & QueryParams<
    "/3/person/{person_id}/combined_credits",
    "get"
  >,
) {
  const { person_id, ...queryParams } = params;
  return tmdbGet("/3/person/{person_id}/combined_credits", queryParams, {
    person_id,
  });
}

export async function getPersonDetails(
  params: { person_id: string } & QueryParams<"/3/person/{person_id}", "get">,
) {
  const { person_id, ...queryParams } = params;
  return tmdbGet("/3/person/{person_id}", queryParams, { person_id });
}

export async function getTrendingMovies(
  params: { time_window: string } & QueryParams<
    "/3/trending/movie/{time_window}",
    "get"
  >,
) {
  const { time_window, ...queryParams } = params;
  return tmdbGet("/3/trending/movie/{time_window}", queryParams, {
    time_window,
  });
}

export async function getTrendingTvShows(
  params: { time_window: string } & QueryParams<
    "/3/trending/tv/{time_window}",
    "get"
  >,
) {
  const { time_window, ...queryParams } = params;
  return tmdbGet("/3/trending/tv/{time_window}", queryParams, { time_window });
}

export async function getTvShowCredits(
  params: { series_id: string } & QueryParams<
    "/3/tv/{series_id}/credits",
    "get"
  >,
) {
  const { series_id, ...queryParams } = params;
  return tmdbGet("/3/tv/{series_id}/credits", queryParams, { series_id });
}

export async function getTvShowDetails(
  params: { series_id: string } & QueryParams<"/3/tv/{series_id}", "get">,
) {
  const { series_id, ...queryParams } = params;
  return tmdbGet("/3/tv/{series_id}", queryParams, { series_id });
}

export async function getTvShowGenres(
  params?: QueryParams<"/3/genre/tv/list", "get">,
) {
  return tmdbGet("/3/genre/tv/list", params);
}

export async function getTvShowRecommendations(
  params: { series_id: string } & QueryParams<
    "/3/tv/{series_id}/recommendations",
    "get"
  >,
) {
  const { series_id, ...queryParams } = params;
  return tmdbGet("/3/tv/{series_id}/recommendations", queryParams, {
    series_id,
  });
}

export async function getTvShowReviews(
  params: { series_id: string } & QueryParams<
    "/3/tv/{series_id}/reviews",
    "get"
  >,
) {
  const { series_id, ...queryParams } = params;
  return tmdbGet("/3/tv/{series_id}/reviews", queryParams, { series_id });
}

export async function getTvShowVideos(
  params: { series_id: string } & QueryParams<
    "/3/tv/{series_id}/videos",
    "get"
  >,
) {
  const { series_id, ...queryParams } = params;
  return tmdbGet("/3/tv/{series_id}/videos", queryParams, { series_id });
}

export async function getTvShowWatchProviders(
  params: { series_id: string } & QueryParams<
    "/3/tv/{series_id}/watch/providers",
    "get"
  >,
) {
  const { series_id, ...queryParams } = params;
  return tmdbGet("/3/tv/{series_id}/watch/providers", queryParams, {
    series_id,
  });
}

export async function searchMulti(
  params: QueryParams<"/3/search/multi", "get">,
) {
  return tmdbGet("/3/search/multi", params);
}
