import { apiRequestWrapper } from "../utils/api-request-wrapper";
import type * as server from "./tmdb-server-functions";

/**
 * Client functions for TMDB APIs - each one has the signature of the server
 * function with the same name, and calls it through its API route.
 *
 * This file is auto-generated by packages/tmdb-codegen/src/generator.js
 * Do not edit manually - changes will be overwritten.
 */

export const discoverMovies: typeof server.discoverMovies = (params) =>
  apiRequestWrapper<typeof server.discoverMovies>(
    "/api/tmdb/discover-movies",
    params,
  );

export const discoverTvShows: typeof server.discoverTvShows = (params) =>
  apiRequestWrapper<typeof server.discoverTvShows>(
    "/api/tmdb/discover-tv-shows",
    params,
  );

export const getConfiguration: typeof server.getConfiguration = (params) =>
  apiRequestWrapper<typeof server.getConfiguration>(
    "/api/tmdb/get-configuration",
    params,
  );

export const getMovieCredits: typeof server.getMovieCredits = (params) =>
  apiRequestWrapper<typeof server.getMovieCredits>(
    "/api/tmdb/get-movie-credits",
    params,
  );

export const getMovieDetails: typeof server.getMovieDetails = (params) =>
  apiRequestWrapper<typeof server.getMovieDetails>(
    "/api/tmdb/get-movie-details",
    params,
  );

export const getMovieGenres: typeof server.getMovieGenres = (params) =>
  apiRequestWrapper<typeof server.getMovieGenres>(
    "/api/tmdb/get-movie-genres",
    params,
  );

export const getMovieRecommendations: typeof server.getMovieRecommendations = (
  params,
) =>
  apiRequestWrapper<typeof server.getMovieRecommendations>(
    "/api/tmdb/get-movie-recommendations",
    params,
  );

export const getMovieVideos: typeof server.getMovieVideos = (params) =>
  apiRequestWrapper<typeof server.getMovieVideos>(
    "/api/tmdb/get-movie-videos",
    params,
  );

export const getPersonCombinedCredits: typeof server.getPersonCombinedCredits =
  (params) =>
    apiRequestWrapper<typeof server.getPersonCombinedCredits>(
      "/api/tmdb/get-person-combined-credits",
      params,
    );

export const getPersonDetails: typeof server.getPersonDetails = (params) =>
  apiRequestWrapper<typeof server.getPersonDetails>(
    "/api/tmdb/get-person-details",
    params,
  );

export const getTvShowCredits: typeof server.getTvShowCredits = (params) =>
  apiRequestWrapper<typeof server.getTvShowCredits>(
    "/api/tmdb/get-tv-show-credits",
    params,
  );

export const getTvShowDetails: typeof server.getTvShowDetails = (params) =>
  apiRequestWrapper<typeof server.getTvShowDetails>(
    "/api/tmdb/get-tv-show-details",
    params,
  );

export const getTvShowGenres: typeof server.getTvShowGenres = (params) =>
  apiRequestWrapper<typeof server.getTvShowGenres>(
    "/api/tmdb/get-tv-genres",
    params,
  );

export const getTvShowRecommendations: typeof server.getTvShowRecommendations =
  (params) =>
    apiRequestWrapper<typeof server.getTvShowRecommendations>(
      "/api/tmdb/get-tv-show-recommendations",
      params,
    );

export const getTvShowVideos: typeof server.getTvShowVideos = (params) =>
  apiRequestWrapper<typeof server.getTvShowVideos>(
    "/api/tmdb/get-tv-show-videos",
    params,
  );
