/**
 * Auto-generated API route for TMDB getPersonDetails
 *
 * This file is auto-generated by tooling/tmdb-codegen/generator.js
 * Do not edit manually - changes will be overwritten.
 */

import { getPersonDetails } from "#src/_generated/tmdb-server-functions.ts";
import { apiRouteWrapper } from "#src/utils/api-route-wrapper.ts";

export const GET = apiRouteWrapper(getPersonDetails);
