/** The `Doc` suffix also keeps a name such as `switch` off a reserved word. */
function toLocalName(name: string): string {
  const [first = "", ...rest] = name.split("-");
  const camel =
    first +
    rest.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("");
  return `${camel}Doc`;
}

/**
 * The module that gathers every generated document into one record, keyed by
 * the `@tuja/ui` export subpath name.
 */
export function renderPropsIndex(names: readonly string[]): string {
  const sorted = [...names].sort((a, b) => a.localeCompare(b));
  return [
    "// AUTO-GENERATED by packages/props-codegen — do not edit.",
    "// To regenerate: pnpm --filter web codegen:props",
    "",
    'import type { PropsDoc } from "@tuja/props-codegen/types";',
    ...sorted.map(
      (name) => `import ${toLocalName(name)} from "./${name}.json";`,
    ),
    "",
    "// A JSON import widens every string, so `kind` arrives as `string` instead",
    "// of the union. The assertion gives the union back.",
    "export const PROPS_DOCS = {",
    ...sorted.map((name) => `  "${name}": ${toLocalName(name)},`),
    "} as Record<string, PropsDoc>;",
    "",
  ].join("\n");
}
