/**
 * Accessory tiles. 32×32 art-pixels.
 * Palette slots: a = accessory primary, b = accessory secondary.
 */

// Antenna accessory — single bobbed antenna sprouting from the head.
export const antennaAccessory = {
  id: "antenna",
  label: { en: "Antenna", zh: "触角" },
  tile: [
    "                                ",
    "               bbb              ",
    "              bbbbb             ",
    "               bbb              ",
    "                a               ",
    "                a               ",
    "                a               ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
};

// Bow accessory — small bow perched on the side of the head.
export const bowAccessory = {
  id: "bow",
  label: { en: "Bow", zh: "蝴蝶结" },
  tile: [
    "                                ",
    "                                ",
    "                                ",
    "         aa            aa       ",
    "        aaaa          aaaa      ",
    "        aabba        abbaa      ",
    "         aabbaa    aabbaa       ",
    "           aabba  abbaa         ",
    "             abbaabba           ",
    "              abbbba            ",
    "             abbaabba           ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
};

// Glasses accessory — round goggles aligned with eye row.
export const glassesAccessory = {
  id: "glasses",
  label: { en: "Glasses", zh: "眼镜" },
  tile: [
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "          aaaaa    aaaaa        ",
    "         abbbbba  abbbbba       ",
    "         ab   ba  ab   ba       ",
    "         ab   ba  ab   ba       ",
    "         abbbbba  abbbbba       ",
    "          aaaaaaaaaaaaaa        ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
};

// Hat accessory — small pointed cap sits on top of the head crown.
export const hatAccessory = {
  id: "hat",
  label: { en: "Hat", zh: "帽子" },
  tile: [
    "                                ",
    "                aa              ",
    "               aaaa             ",
    "              aaaaaa            ",
    "             aaaaaaaa           ",
    "          bbbbbbbbbbbbbb        ",
    "          bbbbbbbbbbbbbb        ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
};

// Leaf-on-head accessory — small leaf perched on top of the head.
export const leafAccessory = {
  id: "leaf",
  label: { en: "Leaf", zh: "叶子" },
  tile: [
    "                                ",
    "                aa              ",
    "               aabba            ",
    "              aabbbba           ",
    "             aabbbbbba          ",
    "              aabbbba           ",
    "               aabba            ",
    "                aa              ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
};

// Scarf accessory — wraps around the neck (between head and body).
export const scarfAccessory = {
  id: "scarf",
  label: { en: "Scarf", zh: "围巾" },
  tile: [
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "       aaaaaaaaaaaaaaaaa        ",
    "      babababababababababa      ",
    "       aaaaaaaaaaaaaaaaa        ",
    "             aaaa               ",
    "             abba               ",
    "             abba               ",
    "             aaaa               ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
  ],
};
