#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  argbFromHex,
  hexFromArgb,
} from "../../src/vendor/material-color-utilities/string_utils.ts";
import { TonalPalette } from "../../src/vendor/material-color-utilities/tonal_palette.ts";
import { pickForeground } from "./contrast.ts";
import { evaluateCurve, SYSTEM_HUES, SYSTEM_PALETTE_TONES } from "./source.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.join(__dirname, "../..");
const outputPath = path.join(
  projectRoot,
  "src",
  "_generated",
  "system-palette.ts",
);

function generate(): string {
  const entries = SYSTEM_HUES.map((hue) => {
    const palette = TonalPalette.fromInt(argbFromHex(hue.source));
    const tones = SYSTEM_PALETTE_TONES.map((t) => {
      const shift = evaluateCurve(t, hue.curve);
      const adjusted = Math.max(0, Math.min(100, t + shift));
      const bg = hexFromArgb(palette.tone(adjusted)).toUpperCase();
      const fg = pickForeground(bg);
      return [t, bg, fg] as const;
    });
    const toneEntries = tones
      .map(([t, bg, fg]) => `    ${String(t)}: { bg: "${bg}", fg: "${fg}" },`)
      .join("\n");
    return `  {
    name: "${hue.name}",
    source: "${hue.source}",
    tones: {
${toneEntries}
    },
  }`;
  }).join(",\n");

  const tonesLiteral = SYSTEM_PALETTE_TONES.join(", ");

  return `// AUTO-GENERATED by tooling/system-palette-codegen — do not edit.
// To regenerate: pnpm codegen:palette

export const SYSTEM_PALETTE_TONES = [${tonesLiteral}] as const;

export type SystemPaletteTone = (typeof SYSTEM_PALETTE_TONES)[number];

export interface SystemToneSwatch {
  readonly bg: string;
  readonly fg: string;
}

export interface SystemHuePalette {
  readonly name: string;
  readonly source: string;
  readonly tones: Readonly<Record<SystemPaletteTone, SystemToneSwatch>>;
}

export const systemPalette: readonly SystemHuePalette[] = [
${entries},
];
`;
}

const output = generate();
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output, "utf8");
console.log(`Wrote ${outputPath}`);
