interface SyntheticCategory {
  key: string;
  kind: "expense" | "income";
  name: string;
  emoji: string;
  color: string;
  /** The key of the parent category; roots have none. */
  parent?: string;
}

export const SYNTHETIC_CATEGORIES: readonly SyntheticCategory[] = [
  { key: "food", kind: "expense", name: "食品", emoji: "🛒", color: "#4c9a6a" },
  {
    key: "grocery",
    kind: "expense",
    name: "超市",
    emoji: "🥬",
    color: "#4c9a6a",
    parent: "food",
  },
  {
    key: "dining",
    kind: "expense",
    name: "下馆子",
    emoji: "🍜",
    color: "#4c9a6a",
    parent: "food",
  },
  {
    key: "takeaway",
    kind: "expense",
    name: "外卖",
    emoji: "🥡",
    color: "#4c9a6a",
    parent: "food",
  },
  {
    key: "coffee",
    kind: "expense",
    name: "咖啡",
    emoji: "☕",
    color: "#4c9a6a",
    parent: "food",
  },

  {
    key: "transport",
    kind: "expense",
    name: "出行",
    emoji: "🚇",
    color: "#3f7fbf",
  },
  {
    key: "transit",
    kind: "expense",
    name: "公共交通",
    emoji: "🚌",
    color: "#3f7fbf",
    parent: "transport",
  },
  {
    key: "taxi",
    kind: "expense",
    name: "打车",
    emoji: "🚕",
    color: "#3f7fbf",
    parent: "transport",
  },
  {
    key: "rail",
    kind: "expense",
    name: "火车",
    emoji: "🚆",
    color: "#3f7fbf",
    parent: "transport",
  },
  {
    key: "fuel",
    kind: "expense",
    name: "油费",
    emoji: "⛽",
    color: "#3f7fbf",
    parent: "transport",
  },

  { key: "home", kind: "expense", name: "居家", emoji: "🏠", color: "#c0783a" },
  {
    key: "mortgageInterest",
    kind: "expense",
    name: "房贷利息",
    emoji: "🏦",
    color: "#c0783a",
    parent: "home",
  },
  {
    key: "councilTax",
    kind: "expense",
    name: "市政税",
    emoji: "🏛",
    color: "#c0783a",
    parent: "home",
  },
  {
    key: "utilities",
    kind: "expense",
    name: "水电煤",
    emoji: "💡",
    color: "#c0783a",
    parent: "home",
  },
  {
    key: "broadband",
    kind: "expense",
    name: "网络",
    emoji: "📶",
    color: "#c0783a",
    parent: "home",
  },
  {
    key: "household",
    kind: "expense",
    name: "家居",
    emoji: "🛋",
    color: "#c0783a",
    parent: "home",
  },

  {
    key: "subscriptions",
    kind: "expense",
    name: "订阅",
    emoji: "📺",
    color: "#8a5bbf",
  },
  {
    key: "streaming",
    kind: "expense",
    name: "影音",
    emoji: "🎬",
    color: "#8a5bbf",
    parent: "subscriptions",
  },
  {
    key: "cloud",
    kind: "expense",
    name: "云服务",
    emoji: "☁️",
    color: "#8a5bbf",
    parent: "subscriptions",
  },

  {
    key: "shopping",
    kind: "expense",
    name: "购物",
    emoji: "🛍",
    color: "#c24f6e",
  },
  {
    key: "online",
    kind: "expense",
    name: "网购",
    emoji: "📦",
    color: "#c24f6e",
    parent: "shopping",
  },
  {
    key: "clothing",
    kind: "expense",
    name: "服饰",
    emoji: "👕",
    color: "#c24f6e",
    parent: "shopping",
  },
  {
    key: "gifts",
    kind: "expense",
    name: "礼物",
    emoji: "🎁",
    color: "#c24f6e",
    parent: "shopping",
  },

  {
    key: "travel",
    kind: "expense",
    name: "旅行",
    emoji: "✈️",
    color: "#2a9d9d",
  },
  {
    key: "flights",
    kind: "expense",
    name: "机票",
    emoji: "🛫",
    color: "#2a9d9d",
    parent: "travel",
  },
  {
    key: "lodging",
    kind: "expense",
    name: "住宿",
    emoji: "🏨",
    color: "#2a9d9d",
    parent: "travel",
  },

  {
    key: "health",
    kind: "expense",
    name: "健康",
    emoji: "💊",
    color: "#d1495b",
  },
  {
    key: "pharmacy",
    kind: "expense",
    name: "药店",
    emoji: "💊",
    color: "#d1495b",
    parent: "health",
  },
  {
    key: "fitness",
    kind: "expense",
    name: "健身",
    emoji: "🏋",
    color: "#d1495b",
    parent: "health",
  },
  {
    key: "clinic",
    kind: "expense",
    name: "医疗",
    emoji: "🦷",
    color: "#d1495b",
    parent: "health",
  },

  { key: "fun", kind: "expense", name: "娱乐", emoji: "🎟", color: "#e0a526" },
  {
    key: "events",
    kind: "expense",
    name: "演出电影",
    emoji: "🎭",
    color: "#e0a526",
    parent: "fun",
  },

  {
    key: "salary",
    kind: "income",
    name: "工资",
    emoji: "💼",
    color: "#2f8f5b",
  },
  {
    key: "monthlyPay",
    kind: "income",
    name: "月薪",
    emoji: "💷",
    color: "#2f8f5b",
    parent: "salary",
  },
  {
    key: "investmentIncome",
    kind: "income",
    name: "理财收入",
    emoji: "📈",
    color: "#2f8f5b",
  },
  {
    key: "interest",
    kind: "income",
    name: "利息",
    emoji: "🪙",
    color: "#2f8f5b",
    parent: "investmentIncome",
  },
  {
    key: "otherIncome",
    kind: "income",
    name: "其他收入",
    emoji: "💰",
    color: "#2f8f5b",
  },
  {
    key: "reimbursement",
    kind: "income",
    name: "报销",
    emoji: "🧾",
    color: "#2f8f5b",
    parent: "otherIncome",
  },
  {
    key: "secondHand",
    kind: "income",
    name: "二手转让",
    emoji: "♻️",
    color: "#2f8f5b",
    parent: "otherIncome",
  },
];
