import type { SYNTHETIC_TAGS } from "./synthetic-tags.ts";

export interface SyntheticPayee {
  name: string;
  /** The key of the usual category. */
  category: string;
  /** How often the payee turns up among random spending; 0 means only rules and special rows use it. */
  weight: number;
  /** The usual amount in pounds. */
  median: number;
  /** The spread of the amount: the standard deviation of its logarithm. */
  spread: number;
  /** How a bank prints the payee; becomes an alias. */
  bankText?: string;
  /** Tag added to most of its transactions. */
  tag?: (typeof SYNTHETIC_TAGS)[number];
  /** Purchases that can be returned for a refund. */
  retail?: boolean;
}

export const SYNTHETIC_PAYEES: readonly SyntheticPayee[] = [
  {
    name: "Tesco",
    category: "grocery",
    weight: 10,
    median: 28,
    spread: 0.6,
    bankText: "TESCO STORES 3214",
  },
  {
    name: "Sainsbury's",
    category: "grocery",
    weight: 6,
    median: 34,
    spread: 0.55,
    bankText: "SAINSBURYS S/MKTS 0417",
  },
  {
    name: "Waitrose",
    category: "grocery",
    weight: 4,
    median: 45,
    spread: 0.5,
    bankText: "WAITROSE 612",
  },
  {
    name: "Ocado",
    category: "grocery",
    weight: 2.5,
    median: 95,
    spread: 0.3,
    bankText: "OCADO RETAIL LTD",
  },
  {
    name: "Lidl",
    category: "grocery",
    weight: 4,
    median: 24,
    spread: 0.5,
    bankText: "LIDL GB LONDON",
  },
  {
    name: "Aldi",
    category: "grocery",
    weight: 3,
    median: 26,
    spread: 0.5,
    bankText: "ALDI STORES 0092",
  },
  {
    name: "M&S Food",
    category: "grocery",
    weight: 3,
    median: 18,
    spread: 0.5,
    bankText: "M&S SIMPLY FOOD 0311",
  },

  {
    name: "Dishoom",
    category: "dining",
    weight: 1.2,
    median: 70,
    spread: 0.35,
    bankText: "DISHOOM LTD",
  },
  {
    name: "Wagamama",
    category: "dining",
    weight: 1.2,
    median: 48,
    spread: 0.3,
    bankText: "WAGAMAMA 0045",
  },
  {
    name: "Nando's",
    category: "dining",
    weight: 1.5,
    median: 34,
    spread: 0.35,
    bankText: "NANDOS 1182",
    tag: "Date night",
  },
  {
    name: "Pizza Express",
    category: "dining",
    weight: 1,
    median: 40,
    spread: 0.35,
    bankText: "PIZZA EXPRESS 0233",
  },
  {
    name: "Pret A Manger",
    category: "dining",
    weight: 4,
    median: 7.5,
    spread: 0.3,
    bankText: "PRET A MANGER 0519",
  },
  {
    name: "Greggs",
    category: "dining",
    weight: 2,
    median: 5,
    spread: 0.35,
    bankText: "GREGGS PLC 2210",
  },

  {
    name: "Starbucks",
    category: "coffee",
    weight: 2.5,
    median: 5,
    spread: 0.3,
    bankText: "STARBUCKS 0841",
  },
  {
    name: "Costa Coffee",
    category: "coffee",
    weight: 2,
    median: 4.5,
    spread: 0.3,
    bankText: "COSTA COFFEE 6120",
  },

  {
    name: "Deliveroo",
    category: "takeaway",
    weight: 4,
    median: 26,
    spread: 0.4,
    bankText: "DELIVEROO PLC",
  },
  {
    name: "Uber Eats",
    category: "takeaway",
    weight: 2.5,
    median: 24,
    spread: 0.4,
    bankText: "UBER *EATS HELP.UBER.COM",
  },

  {
    name: "TfL",
    category: "transit",
    weight: 9,
    median: 7.5,
    spread: 0.35,
    bankText: "TFL TRAVEL CH",
  },
  {
    name: "Uber",
    category: "taxi",
    weight: 2.5,
    median: 16,
    spread: 0.5,
    bankText: "UBER *TRIP HELP.UBER.COM",
  },
  {
    name: "Trainline",
    category: "rail",
    weight: 1,
    median: 38,
    spread: 0.6,
    bankText: "TRAINLINE.COM",
  },
  {
    name: "Shell",
    category: "fuel",
    weight: 1.2,
    median: 62,
    spread: 0.25,
    bankText: "SHELL KENSINGTON",
    tag: "Car",
  },

  {
    name: "Amazon",
    category: "online",
    weight: 7,
    median: 24,
    spread: 0.8,
    bankText: "AMAZON.CO.UK*2K4TY8",
    retail: true,
  },
  {
    name: "John Lewis",
    category: "household",
    weight: 1,
    median: 70,
    spread: 0.6,
    bankText: "JOHN LEWIS 0058",
    retail: true,
  },
  {
    name: "IKEA",
    category: "household",
    weight: 0.7,
    median: 85,
    spread: 0.7,
    bankText: "IKEA LTD WEMBLEY",
    tag: "Home project",
    retail: true,
  },
  {
    name: "Argos",
    category: "household",
    weight: 0.6,
    median: 40,
    spread: 0.6,
    bankText: "ARGOS 0413",
    retail: true,
  },
  {
    name: "Apple Store",
    category: "online",
    weight: 0.4,
    median: 65,
    spread: 0.8,
    bankText: "APPLE.COM/BILL",
    retail: true,
  },
  {
    name: "H&M",
    category: "clothing",
    weight: 1,
    median: 35,
    spread: 0.5,
    bankText: "H&M 0341",
    retail: true,
  },
  {
    name: "Uniqlo",
    category: "clothing",
    weight: 0.8,
    median: 55,
    spread: 0.45,
    bankText: "UNIQLO UK LTD",
    retail: true,
  },

  {
    name: "Boots",
    category: "pharmacy",
    weight: 3,
    median: 14,
    spread: 0.5,
    bankText: "BOOTS 1127",
  },
  {
    name: "Smile Dental",
    category: "clinic",
    weight: 0,
    median: 85,
    spread: 0.2,
    bankText: "SMILE DENTAL PRACTICE",
  },
  {
    name: "Odeon",
    category: "events",
    weight: 0.8,
    median: 24,
    spread: 0.3,
    bankText: "ODEON CINEMAS",
    tag: "Date night",
  },
  {
    name: "Ticketmaster",
    category: "events",
    weight: 0.5,
    median: 90,
    spread: 0.4,
    bankText: "TICKETMASTER UK",
  },

  {
    name: "Airbnb",
    category: "lodging",
    weight: 0.15,
    median: 420,
    spread: 0.4,
    bankText: "AIRBNB * HM4TX",
    tag: "Holiday",
  },
  {
    name: "Booking.com",
    category: "lodging",
    weight: 0.1,
    median: 380,
    spread: 0.4,
    bankText: "BOOKING.COM HOTEL",
    tag: "Holiday",
  },
  {
    name: "British Airways",
    category: "flights",
    weight: 0.1,
    median: 310,
    spread: 0.4,
    bankText: "BRITISH AIRWAYS",
    tag: "Holiday",
  },
  {
    name: "easyJet",
    category: "flights",
    weight: 0.15,
    median: 180,
    spread: 0.4,
    bankText: "EASYJET000 LUTON",
    tag: "Holiday",
  },

  {
    name: "Netflix",
    category: "streaming",
    weight: 0,
    median: 10.99,
    spread: 0,
    bankText: "NETFLIX.COM",
  },
  {
    name: "Spotify",
    category: "streaming",
    weight: 0,
    median: 11.99,
    spread: 0,
    bankText: "SPOTIFY P1A2B3",
  },
  {
    name: "Disney+",
    category: "streaming",
    weight: 0,
    median: 7.99,
    spread: 0,
    bankText: "DISNEY PLUS",
  },
  {
    name: "Amazon Prime",
    category: "streaming",
    weight: 0,
    median: 8.99,
    spread: 0,
    bankText: "AMZNPRIME MEMBERSHIP",
  },
  {
    name: "iCloud",
    category: "cloud",
    weight: 0,
    median: 2.99,
    spread: 0,
    bankText: "APPLE.COM/BILL ICLOUD",
  },
  {
    name: "PureGym",
    category: "fitness",
    weight: 0,
    median: 35,
    spread: 0,
    bankText: "PUREGYM LTD",
  },
  {
    name: "Octopus Energy",
    category: "utilities",
    weight: 0,
    median: 140,
    spread: 0,
    bankText: "OCTOPUS ENERGY",
  },
  {
    name: "Thames Water",
    category: "utilities",
    weight: 0,
    median: 38,
    spread: 0,
    bankText: "THAMES WATER",
  },
  {
    name: "BT",
    category: "broadband",
    weight: 0,
    median: 32,
    spread: 0,
    bankText: "BT GROUP PLC",
  },
  {
    name: "Local Council",
    category: "councilTax",
    weight: 0,
    median: 165,
    spread: 0,
    bankText: "LB COUNCIL TAX",
  },
  {
    name: "Northbank Mortgage",
    category: "mortgageInterest",
    weight: 0,
    median: 650,
    spread: 0,
    bankText: "NORTHBANK MORTGAGES",
  },

  {
    name: "Acme Ltd",
    category: "monthlyPay",
    weight: 0,
    median: 3650,
    spread: 0,
    bankText: "ACME LTD SALARY",
  },
  {
    name: "Brightside Studio",
    category: "monthlyPay",
    weight: 0,
    median: 2780,
    spread: 0,
    bankText: "BRIGHTSIDE STUDIO LTD",
  },
  {
    name: "Harbour Bank",
    category: "interest",
    weight: 0,
    median: 48,
    spread: 0,
    bankText: "HARBOUR BANK INTEREST",
  },
  {
    name: "Vinted",
    category: "secondHand",
    weight: 0,
    median: 22,
    spread: 0.5,
    bankText: "VINTED UAB",
  },
];
