import type { SyntheticOwner } from "./synthetic-accounts.ts";

export interface SyntheticRule {
  key: string;
  name: string;
  dayOfMonth: number;
  kind: "expense" | "income" | "transfer";
  /** In pounds, positive. */
  amount: number;
  category?: string;
  payee?: string;
  /** The account the money leaves, or for an income the account it enters. */
  account: string;
  /** For a transfer, the account the money enters. */
  toAccount?: string;
  member: SyntheticOwner;
  autoPost: boolean;
  /** Each past occurrence differs from the template by up to this fraction. */
  varies?: number;
}

export const SYNTHETIC_RULES: readonly SyntheticRule[] = [
  {
    key: "salaryAlex",
    name: "Alex salary",
    dayOfMonth: 25,
    kind: "income",
    amount: 3650,
    category: "monthlyPay",
    payee: "Acme Ltd",
    account: "alexCurrent",
    member: "alex",
    autoPost: true,
  },
  {
    key: "salarySam",
    name: "Sam salary",
    dayOfMonth: 28,
    kind: "income",
    amount: 2780,
    category: "monthlyPay",
    payee: "Brightside Studio",
    account: "samCurrent",
    member: "sam",
    autoPost: true,
  },
  {
    key: "savingsInterest",
    name: "Savings interest",
    dayOfMonth: 28,
    kind: "income",
    amount: 48,
    category: "interest",
    payee: "Harbour Bank",
    account: "savings",
    member: null,
    autoPost: true,
    varies: 0.1,
  },
  {
    key: "mortgageInterest",
    name: "Mortgage interest",
    dayOfMonth: 1,
    kind: "expense",
    amount: 650,
    category: "mortgageInterest",
    payee: "Northbank Mortgage",
    account: "alexCurrent",
    member: null,
    autoPost: true,
  },
  {
    key: "mortgagePrincipal",
    name: "Mortgage principal",
    dayOfMonth: 1,
    kind: "transfer",
    amount: 400,
    account: "alexCurrent",
    toAccount: "mortgage",
    member: null,
    autoPost: true,
  },
  {
    key: "councilTax",
    name: "Council tax",
    dayOfMonth: 1,
    kind: "expense",
    amount: 165,
    category: "councilTax",
    payee: "Local Council",
    account: "alexCurrent",
    member: null,
    autoPost: true,
  },
  {
    key: "energy",
    name: "Energy",
    dayOfMonth: 15,
    kind: "expense",
    amount: 140,
    category: "utilities",
    payee: "Octopus Energy",
    account: "alexCurrent",
    member: null,
    autoPost: false,
    varies: 0.2,
  },
  {
    key: "water",
    name: "Water",
    dayOfMonth: 18,
    kind: "expense",
    amount: 38,
    category: "utilities",
    payee: "Thames Water",
    account: "alexCurrent",
    member: null,
    autoPost: false,
  },
  {
    key: "broadband",
    name: "Broadband",
    dayOfMonth: 20,
    kind: "expense",
    amount: 32,
    category: "broadband",
    payee: "BT",
    account: "alexCurrent",
    member: null,
    autoPost: true,
  },
  {
    key: "netflix",
    name: "Netflix",
    dayOfMonth: 8,
    kind: "expense",
    amount: 10.99,
    category: "streaming",
    payee: "Netflix",
    account: "visa",
    member: "alex",
    autoPost: true,
  },
  {
    key: "spotify",
    name: "Spotify",
    dayOfMonth: 14,
    kind: "expense",
    amount: 11.99,
    category: "streaming",
    payee: "Spotify",
    account: "mastercard",
    member: "sam",
    autoPost: true,
  },
  {
    key: "disney",
    name: "Disney+",
    dayOfMonth: 21,
    kind: "expense",
    amount: 7.99,
    category: "streaming",
    payee: "Disney+",
    account: "amex",
    member: null,
    autoPost: true,
  },
  {
    key: "prime",
    name: "Amazon Prime",
    dayOfMonth: 11,
    kind: "expense",
    amount: 8.99,
    category: "streaming",
    payee: "Amazon Prime",
    account: "amex",
    member: null,
    autoPost: true,
  },
  {
    key: "icloud",
    name: "iCloud storage",
    dayOfMonth: 3,
    kind: "expense",
    amount: 2.99,
    category: "cloud",
    payee: "iCloud",
    account: "visa",
    member: "alex",
    autoPost: true,
  },
  {
    key: "gym",
    name: "Gym",
    dayOfMonth: 1,
    kind: "expense",
    amount: 35,
    category: "fitness",
    payee: "PureGym",
    account: "mastercard",
    member: "sam",
    autoPost: true,
  },
  {
    key: "savingsAlex",
    name: "Alex to savings",
    dayOfMonth: 26,
    kind: "transfer",
    amount: 300,
    account: "alexCurrent",
    toAccount: "savings",
    member: "alex",
    autoPost: true,
  },
  {
    key: "savingsSam",
    name: "Sam to savings",
    dayOfMonth: 27,
    kind: "transfer",
    amount: 600,
    account: "samCurrent",
    toAccount: "savings",
    member: "sam",
    autoPost: true,
  },
  {
    key: "isaAlex",
    name: "Alex ISA contribution",
    dayOfMonth: 2,
    kind: "transfer",
    amount: 250,
    account: "alexCurrent",
    toAccount: "alexIsa",
    member: "alex",
    autoPost: true,
  },
  {
    key: "isaSam",
    name: "Sam ISA contribution",
    dayOfMonth: 2,
    kind: "transfer",
    amount: 200,
    account: "samCurrent",
    toAccount: "samIsa",
    member: "sam",
    autoPost: true,
  },
];
