/**
 * Auto-generated API route for TMDB getMovieVideos
 *
 * This file is auto-generated by packages/tmdb-codegen/generator.js
 * Do not edit manually - changes will be overwritten.
 */

import { getMovieVideos } from "#src/_generated/tmdb-server-functions.ts";
import { apiRouteWrapper } from "#src/utils/api-route-wrapper.ts";

export const GET = apiRouteWrapper(getMovieVideos);
