/**
 * Auto-generated API route for TMDB getTvShowGenres
 *
 * This file is auto-generated by tooling/tmdb-codegen/generator.js
 * Do not edit manually - changes will be overwritten.
 */

import { getTvShowGenres } from "@/_generated/tmdb-server-functions";
import { apiRouteWrapper } from "@/utils/api-route-wrapper";

export const GET = apiRouteWrapper(getTvShowGenres);
