/**
 * Auto-generated API route for TMDB getMovieGenres
 *
 * This file is auto-generated by tooling/tmdb-codegen/generator.js
 * Do not edit manually - changes will be overwritten.
 */

import { getMovieGenres } from "@/_generated/tmdb-server-functions";
import { apiRouteWrapper } from "@/utils/api-route-wrapper";

export const GET = apiRouteWrapper(getMovieGenres);
